/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advancedsoftware;
<<<<<<< HEAD
import java.sql.*;
import javax.swing.JOptionPane;
=======

import javax.swing.JOptionPane;
import java.sql.*;

>>>>>>> a77bbe57509cd48ed16f4b894a42fbcbefb1daa8
/**
 *
 * @author bola-fayz
 */
public class MainFrame extends javax.swing.JFrame {
    
    
    String user = "sa"; 
    String pass = "Bola@1234";
    String databaseName = "SoftCoreDB";
    
//    private final String url = "jdbc:sqlserver://localhost:\\SQLEXPRESS;databaseNmae=" + databaseName 
//            + ";user=" + user + ";password=" + pass + ";";
    

    private final String url = "jdbc:sqlserver://localhost:1433;databaseName=" + databaseName 
        + ";user=" + user + ";password=" + pass 
        + ";encrypt=true;trustServerCertificate=true;";
    
    public static Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
       
    
    private final String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SoftCoreDB;encrypt=true;trustServerCertificate=true";
    String userName = "SWE2DB";
    String passWord = "1234";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        establishConnection();
        initComponents();
        
        
<<<<<<< HEAD
    }
  
    public void establishConnection(){
        try {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(url);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Connecting: " + e.getMessage());
            e.printStackTrace();
        }
=======
        try {
    Connection con = DriverManager.getConnection(url, userName, passWord);
    Statement stmt = con.createStatement();

    stmt.close();
    con.close();

    } catch(SQLException ex){
    ex.printStackTrace();
       }
        
>>>>>>> a77bbe57509cd48ed16f4b894a42fbcbefb1daa8
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboard1 = new advancedsoftware.Dashboard();
        employees1 = new advancedsoftware.Employees();
        projects1 = new advancedsoftware.Projects();
        tasks1 = new advancedsoftware.Tasks();
        clients1 = new advancedsoftware.Clients();
        departments1 = new advancedsoftware.Departments();
        admin_Profile1 = new advancedsoftware.Admin_Profile();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Dashboard", dashboard1);
        jTabbedPane1.addTab("Employees", employees1);
        jTabbedPane1.addTab("Projects", projects1);
        jTabbedPane1.addTab("Tasks", tasks1);
        jTabbedPane1.addTab("Clients", clients1);
        jTabbedPane1.addTab("Departments", departments1);
        jTabbedPane1.addTab("Admin Profile", admin_Profile1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, Short.MAX_VALUE)
=======
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
>>>>>>> b822f8440cfea6ce6209fa1a0c0d7922afa91b2e
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private advancedsoftware.Admin_Profile admin_Profile1;
    private advancedsoftware.Clients clients1;
    private advancedsoftware.Dashboard dashboard1;
    private advancedsoftware.Departments departments1;
    private advancedsoftware.Employees employees1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private advancedsoftware.Projects projects1;
    private advancedsoftware.Tasks tasks1;
    // End of variables declaration//GEN-END:variables
}
